# Generated by Django 2.2.6 on 2019-10-17 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sneakers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sneakers',
            name='model_brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sneakers.Brand', verbose_name='Brand'),
        ),
    ]
